 
name: Build and Test

on:
  label:
    types:
      - created

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Run docker commands
      run: |
        sudo docker stop book-recommendation
        sudo docker rm book-recommendation
        sudo docker build -t new:1.0 .
        sudo docker run -d -p 8501:8501 --name book-recommendation new:1.0
